//world/proc/shelleo
#define SHELLEO_ERRORLEVEL 1
#define SHELLEO_STDOUT 2
#define SHELLEO_STDERR 3

#define CINEMATIC_NSV_SHIP_KABOOM 14 //Nsv13...duh

#define PVP_SYNDIE_WIN 25
#define PVP_SYNDIE_LOSS 26
#define PVP_SYNDIE_PIRATE_WIN 27
#define SHIP_VICTORY 28
#define SHIP_DESTROYED 29
